# Chaves geradas no painel do SonarCloud ao criar o projeto
sonar.organization=helolynha
sonar.projectKey=VendasTG-IA

# Caminho dos arquivos fonte que serão analisados
sonar.sources=app, routes
# Idioma principal do projeto
sonar.language=php
sonar.php.version=8.3

# Pastas que devem ser ignoradas para não inflar as métricas com código de terceiros
sonar.exclusions=vendor/**, storage/**, bootstrap/**, public/**, tests/**, database/**